apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbgrader-exchange
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.exchange.size }}
  storageClassName: {{ .Values.exchange.storageClassName }}
  volumeMode: Filesystem
